name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - type: "pre-exclude"
    when:
      label: "skip-changelog"
      
  - title: "Breaking Changes"
    labels:
      - "breaking change"
    exclusive: true
    
  - title: "Features"
    labels:
      - "feature"
    exclusive: true
    
  - title: "Bug Fixes & Security"
    labels:
      - "bug"
      - "security"
    exclusive: true

  - title: "Improvements"
    labels:
      - "improvement"
    exclusive: true

  - title: "Maintenance"
    labels:
      - "ci"
      - "dependencies"
      - "maintenance"
      - "tests"
      - "documentation"
    exclusive: true
    
  - title: "Other Changes"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## Changes

  $CHANGES