services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raycynix-auth-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:?}
      ASPNETCORE_URLS: http://+:5000

      DatabaseConfiguration__ConnectionConfiguration__Host: ${POSTGRES_HOST:?}
      DatabaseConfiguration__ConnectionConfiguration__Port: ${POSTGRES_PORT:?}
      DatabaseConfiguration__ConnectionConfiguration__Name: ${POSTGRES_DB:?}
      DatabaseConfiguration__ConnectionConfiguration__Username: ${POSTGRES_USER:?}
      DatabaseConfiguration__ConnectionConfiguration__Password: ${POSTGRES_PASSWORD:?}

      SecurityConfiguration__Jwt__Secret: ${JWT_SECRET:?}
      SecurityConfiguration__Jwt__Authority: ${JWT_AUTHORITY:?}
      SecurityConfiguration__Jwt__Issuer: ${JWT_ISSUER:?}
      SecurityConfiguration__Jwt__Audience: ${JWT_AUDIENCE:?}

      EmailConfiguration__SmtpConfiguration__Username: ${SMTP_USERNAME:?}
      EmailConfiguration__SmtpConfiguration__Password: ${SMTP_PASSWORD:?}
    ports:
      - "5000:5000"
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: raycynix-auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    volumes:
      - postgres-auth:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:?} -d ${POSTGRES_DB:?}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres-auth:
