<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <Version>0.1.0</Version>

        <Description>The Auth Service.</Description>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

    <PropertyGroup>
        <PackageIcon>logo.png</PackageIcon>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <Company>Raycynix</Company>
        <Authors>Raycynix</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <Product>$(MSBuildProjectName)</Product>
        <PackageId>$(MSBuildProjectName)</PackageId>

        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>$(MSBuildProjectName)</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <Copyright>Copyright © $([System.DateTime]::Now.Year) Raycynix</Copyright>
        <RepositoryUrl>https://github.com/Raycynix/Services.Template</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Raycynix/Services.Template</PackageProjectUrl>
        <RepositoryType>GitHub</RepositoryType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>

        <SelfContained>true</SelfContained>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)logo.png" Pack="true" Visible="false" PackagePath="\"/>
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
      <PackageReference Include="Raycynix.Extensions.Configuration.AspNetCore" Version="2.0.0" />
      <PackageReference Include="Raycynix.Extensions.Database" Version="2.1.0" />
      <PackageReference Include="Raycynix.Extensions.Database.AspNetCore" Version="2.1.0" />
      <PackageReference Include="Raycynix.Extensions.Database.AspNetCore.Identity" Version="2.1.0" />
      <PackageReference Include="Raycynix.Extensions.Database.PostgreSql" Version="2.1.0" />
      <PackageReference Include="Raycynix.Extensions.Exceptions.AspNetCore" Version="1.0.1" />
      <PackageReference Include="Raycynix.Extensions.Secrets" Version="1.1.0" />
      <PackageReference Include="Raycynix.Extensions.Security.AspNetCore" Version="1.0.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\Exceptions\" />
    </ItemGroup>

    <PropertyGroup>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    </PropertyGroup>
</Project>
