// Copyright 2026 Raycynix
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0

using System.ComponentModel.DataAnnotations;

namespace Raycynix.Services.AuthService.Application.Models;

/// <summary>
/// Represents the data required to register a user.
/// </summary>
/// <param name="UserName">The unique user name.</param>
/// <param name="Email">The user's email address.</param>
/// <param name="Password">The user's password.</param>
public record RegisterRequest(
    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Username is required.")]
    string UserName,
    
    [property: Required]
    [property: EmailAddress]
    string Email,
    
    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Password is required.")]
    string Password);

/// <summary>
/// Represents the credentials required to sign in.
/// </summary>
/// <param name="Login">The user name or email address.</param>
/// <param name="Password">The user's password.</param>
public record LoginRequest(
    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Login is required.")]
    string Login,
    
    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Password is required.")]
    string Password);

/// <summary>
/// Represents the data required to request a new email confirmation link.
/// </summary>
/// <param name="Email">The user's email address.</param>
public record EmailConfirmationLinkRequest(
    [property: Required]
    [property: EmailAddress]
    string Email);

/// <summary>
/// Represents the data required to confirm a user's email address.
/// </summary>
/// <param name="Email">The user's email address.</param>
/// <param name="Token">The email confirmation token generated by ASP.NET Core Identity.</param>
public record ConfirmEmailRequest(
    [property: Required]
    [property: EmailAddress]
    string Email,

    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Token is required.")]
    string Token);

/// <summary>
/// Represents the data required to request a password reset token.
/// </summary>
/// <param name="Email">The user's email address.</param>
public record PasswordResetLinkRequest(
    [property: Required]
    [property: EmailAddress]
    string Email);

/// <summary>
/// Represents the data required to reset a user's password.
/// </summary>
/// <param name="Email">The user's email address.</param>
/// <param name="Token">The password reset token generated by ASP.NET Core Identity.</param>
/// <param name="NewPassword">The new password.</param>
public record ResetPasswordRequest(
    [property: Required]
    [property: EmailAddress]
    string Email,

    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "Token is required.")]
    string Token,

    [property: Required]
    [property: RegularExpression(@".*\S.*", ErrorMessage = "New password is required.")]
    string NewPassword);
