<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>bd08c32a-abff-48c2-9674-6f8fe88c6ed8</UserSecretsId>
    </PropertyGroup>

</Project>
